import React, { createContext, useState, useContext } from 'react';

const LanguageContext = createContext();

export const languages = [
    { code: 'en', name: 'English', nativeName: 'English' },
    { code: 'hi', name: 'Hindi', nativeName: 'हिन्दी' },
    { code: 'pa', name: 'Punjabi', nativeName: 'ਪੰਜਾਬੀ' },
    { code: 'ta', name: 'Tamil', nativeName: 'தமிழ்' },
];

const translations = {
    en: {
        nav: {
            upload: 'Upload Document',
            documents: 'My Documents',
            settings: 'Settings',
            legalAid: 'Legal Aid',
            signout: 'Sign Out',
            features: 'Features',
            howItWorks: 'How it Works',
            testimonials: 'Testimonials',
            signIn: 'Sign In',
            getStarted: 'Get Started',
        },
        landing: {
            hero: {
                badge: 'AI-Powered Legal Assistant 2.0',
                title: 'Legal Intelligence',
                subtitle: 'Reimagined for Everyone',
                description: 'Simplify complex legal documents, get instant advisory, and find legal aid with the power of advanced AI. Secure, fast, and accessible.',
                startFree: 'Start for Free',
                liveDemo: 'Live Demo',
            },
            features: {
                title: 'Why Choose CodeBandhu?',
                subtitle: 'Built specifically for the Indian legal framework to help citizens, students, and professionals.',
                simplification: {
                    title: 'Instant Simplification',
                    desc: 'Translate complex legalese into plain English (and Hindi soon) using our Legal-BERT powered engine.',
                },
                summarization: {
                    title: 'Smart Summarization',
                    desc: 'Get concise summaries that highlight the Issue, Facts, Arguments, and Conclusions automatically.',
                },
                advisory: {
                    title: 'Actionable Advisory',
                    desc: 'Receive non-binding legal suggestions on what steps to take next (e.g., RTI, FIR, Grievance).',
                },
            },
            howItWorks: {
                title: 'How It Works',
                subtitle: 'Get your legal answers in 3 simple steps.',
                step1: { title: 'Upload Document', desc: 'Upload your legal notice, contract, or query securely.' },
                step2: { title: 'AI Analysis', desc: 'Our AI scans, simplifies, and summarizes the content instantly.' },
                step3: { title: 'Get Results', desc: 'Receive a plain English summary and actionable advice.' },
            },
            testimonials: {
                title: 'Trusted by Thousands',
                subtitle: 'See what our users are saying about CodeBandhu.',
            },
            about: {
                mission: 'Our Mission',
                title: 'Bridging the Legal Gap',
                desc1: 'In India, millions of citizens struggle to understand their legal rights due to complex language and lack of accessible resources.',
                desc2: 'CodeBandhu is an AI-powered initiative designed to democratize legal access. We combine cutting-edge Natural Language Processing (NLP) with deep legal expertise to make justice accessible to everyone, from rural citizens to urban professionals.',
                stats: { accuracy: 'Accuracy Rate', availability: 'Availability' },
                citizens: { title: 'For Citizens', desc: 'Understand contracts, notices, and rights in simple language.' },
                legalAid: { title: 'For Legal Aid', desc: 'Accelerate case processing and document review.' },
                ngos: { title: 'For NGOs', desc: 'Empower communities with instant legal literacy tools.' },
            },
            contact: {
                title: 'Get in Touch',
                subtitle: 'Have questions about CodeBandhu? Our team is here to help you navigate the platform.',
                firstName: 'First Name',
                lastName: 'Last Name',
                email: 'Email Address',
                message: 'Message',
                send: 'Send Message',
            },
            footer: {
                desc: 'Making Indian Law simple, accessible, and understandable for everyone through the power of AI.',
                product: 'Product',
                legal: 'Legal',
                privacy: 'Privacy Policy',
                terms: 'Terms of Service',
                disclaimer: 'Disclaimer',
                rights: 'All rights reserved.',
                madeWith: 'Made with ❤️ for India',
            },
        },
        dashboard: {
            title: 'Dashboard',
            welcome: 'Welcome back,',
            subtitle: "Here's what's happening with your legal documents.",
            newAnalysis: 'New Analysis',
            stats: {
                documents: 'Documents Analyzed',
                time: 'Time Saved',
                score: 'Legal Score',
            },
            recentActivity: {
                title: 'Recent Activity',
                viewAll: 'View All',
            },
            quickActions: {
                title: 'Quick Actions',
                upload: 'Upload Document',
                findLawyer: 'Find a Lawyer',
                updateProfile: 'Update Profile',
            },
        },
        upload: {
            title: 'Upload Document',
            subtitle: 'Upload a legal document (PDF) to get started.',
            dragDrop: 'Drag & drop your PDF here',
            browse: 'or click to browse files',
            selectFile: 'Select File',
            process: 'Process Document',
            extracting: 'Extracting Text...',
        },
        legalAid: {
            title: 'Find Legal Aid',
            subtitle: 'Connect with experienced lawyers and legal aid volunteers near you',
            searchPlaceholder: 'Search by name or specialization...',
            selectLocation: 'Select Your Location',
            allCities: 'All Cities',
            selectSpecialization: 'Select Specialization',
            allSpecializations: 'All Specializations',
            found: 'Found',
            providers: 'legal aid providers',
            call: 'Call',
            email: 'Email',
            experience: 'Experience',
            languages: 'Languages',
            availability: 'Availability',
            noResults: 'No legal aid providers found matching your criteria.',
            clearFilters: 'Clear Filters',
        },
        account: {
            title: 'My Account',
            subtitle: 'Manage your profile settings',
            editProfile: 'Edit Profile',
            cancel: 'Cancel',
            firstName: 'First Name',
            lastName: 'Last Name',
            emailAddress: 'Email Address',
            emailCannotChange: 'Email cannot be changed.',
            saveChanges: 'Save Changes',
            freePlan: 'Free Plan',
            updateSuccess: 'Profile updated successfully!',
            updateFailed: 'Failed to update profile.',
        },
        login: {
            title: 'Welcome Back',
            subtitle: 'Sign in to your CodeBandhu account',
            email: 'Email Address',
            password: 'Password',
            rememberMe: 'Remember me',
            forgotPassword: 'Forgot password?',
            signIn: 'Sign In',
            signingIn: 'Signing In...',
            noAccount: "Don't have an account?",
            createAccount: 'Create Account',
            demoCredentials: 'Demo Credentials:',
        },
        signup: {
            title: 'Create Account',
            subtitle: 'Join CodeBandhu today',
            firstName: 'First Name',
            lastName: 'Last Name',
            email: 'Email Address',
            password: 'Password',
            createAccount: 'Create Account',
            creating: 'Creating Account...',
            hasAccount: 'Already have an account?',
            signIn: 'Sign In',
        },
        documents: {
            title: 'My Documents',
            empty: 'No documents found.',
            headers: {
                name: 'Document Name',
                date: 'Date',
                type: 'Type',
                status: 'Status',
                actions: 'Actions',
            },
        },
        processing: {
            title: 'Analyzing Document',
            step1: 'Scanning document structure...',
            step2: 'Identifying legal clauses...',
            step3: 'Simplifying complex language...',
            step4: 'Generating summary...',
            step5: 'Preparing advisory...',
            complete: 'Analysis Complete!',
        },
        results: {
            title: 'Analysis Results',
            back: 'Back to Dashboard',
            tabs: {
                simplification: 'Simplification',
                summary: 'Summary',
                advisory: 'Legal Advisory',
                chat: 'Ask AI',
            },
            simplification: {
                original: 'Original Text',
                simplified: 'Simplified Version',
            },
            summary: {
                issue: 'Legal Issue',
                facts: 'Key Facts',
                arguments: 'Arguments',
                conclusion: 'Conclusion',
            },
            advisory: {
                rights: 'Your Rights',
                actions: 'Recommended Actions',
                risk: 'Risk Assessment',
            },
        },
    },
    hi: {
        nav: {
            upload: 'दस्तावेज़ अपलोड करें',
            documents: 'मेरे दस्तावेज़',
            settings: 'सेटिंग्स',
            legalAid: 'कानूनी सहायता',
            signout: 'साइन आउट',
            features: 'विशेषताएं',
            howItWorks: 'यह कैसे काम करता है',
            testimonials: 'प्रशंसापत्र',
            signIn: 'साइन इन करें',
            getStarted: 'शुरू करें',
        },
        landing: {
            hero: {
                badge: 'एआई-संचालित कानूनी सहायक 2.0',
                title: 'कानूनी बुद्धिमत्ता',
                subtitle: 'सभी के लिए पुनर्कल्पित',
                description: 'जटिल कानूनी दस्तावेजों को सरल बनाएं, तत्काल सलाह प्राप्त करें, और उन्नत एआई की शक्ति के साथ कानूनी सहायता खोजें। सुरक्षित, तेज और सुलभ।',
                startFree: 'मुफ्त में शुरू करें',
                liveDemo: 'लाइव डेमो',
            },
            features: {
                title: 'कोडबंधु क्यों चुनें?',
                subtitle: 'नागरिकों, छात्रों और पेशेवरों की मदद के लिए भारतीय कानूनी ढांचे के लिए विशेष रूप से बनाया गया।',
                simplification: {
                    title: 'तत्काल सरलीकरण',
                    desc: 'हमारे लीगल-बर्ट संचालित इंजन का उपयोग करके जटिल कानूनी भाषा को सरल अंग्रेजी (और जल्द ही हिंदी) में अनुवाद करें।',
                },
                summarization: {
                    title: 'स्मार्ट सारांश',
                    desc: 'संक्षिप्त सारांश प्राप्त करें जो स्वचालित रूप से मुद्दे, तथ्यों, तर्कों और निष्कर्षों को उजागर करते हैं।',
                },
                advisory: {
                    title: 'कार्रवाई योग्य सलाह',
                    desc: 'आगे क्या कदम उठाने हैं (जैसे, आरटीआई, एफआईआर, शिकायत) पर गैर-बाध्यकारी कानूनी सुझाव प्राप्त करें।',
                },
            },
            howItWorks: {
                title: 'यह कैसे काम करता है',
                subtitle: '3 सरल चरणों में अपने कानूनी उत्तर प्राप्त करें।',
                step1: { title: 'दस्तावेज़ अपलोड करें', desc: 'अपना कानूनी नोटिस, अनुबंध, या प्रश्न सुरक्षित रूप से अपलोड करें।' },
                step2: { title: 'एआई विश्लेषण', desc: 'हमारा एआई सामग्री को तुरंत स्कैन, सरल और सारांशित करता है।' },
                step3: { title: 'परिणाम प्राप्त करें', desc: 'एक सरल अंग्रेजी सारांश और कार्रवाई योग्य सलाह प्राप्त करें।' },
            },
            testimonials: {
                title: 'हजारों द्वारा विश्वसनीय',
                subtitle: 'देखें कि हमारे उपयोगकर्ता कोडबंधु के बारे में क्या कह रहे हैं।',
            },
            about: {
                mission: 'हमारा मिशन',
                title: 'कानूनी अंतर को पाटना',
                desc1: 'भारत में, लाखों नागरिक जटिल भाषा और सुलभ संसाधनों की कमी के कारण अपने कानूनी अधिकारों को समझने के लिए संघर्ष करते हैं।',
                desc2: 'कोडबंधु एक एआई-संचालित पहल है जिसे कानूनी पहुंच को लोकतांत्रिक बनाने के लिए डिज़ाइन किया गया है। हम न्याय को सभी के लिए सुलभ बनाने के लिए अत्याधुनिक प्राकृतिक भाषा प्रसंस्करण (एनएलपी) को गहरी कानूनी विशेषज्ञता के साथ जोड़ते हैं।',
                stats: { accuracy: 'सटीकता दर', availability: 'उपलब्धता' },
                citizens: { title: 'नागरिकों के लिए', desc: 'सरल भाषा में अनुबंध, नोटिस और अधिकारों को समझें।' },
                legalAid: { title: 'कानूनी सहायता के लिए', desc: 'मामले की प्रक्रिया और दस्तावेज़ समीक्षा में तेजी लाएं।' },
                ngos: { title: 'एनजीओ के लिए', desc: 'तत्काल कानूनी साक्षरता उपकरणों के साथ समुदायों को सशक्त बनाएं।' },
            },
            contact: {
                title: 'संपर्क करें',
                subtitle: 'कोडबंधु के बारे में प्रश्न हैं? हमारी टीम प्लेटफॉर्म को नेविगेट करने में आपकी मदद करने के लिए यहां है।',
                firstName: 'पहला नाम',
                lastName: 'अंतिम नाम',
                email: 'ईमेल पता',
                message: 'संदेश',
                send: 'संदेश भेजें',
            },
            footer: {
                desc: 'एआई की शक्ति के माध्यम से भारतीय कानून को सभी के लिए सरल, सुलभ और समझने योग्य बनाना।',
                product: 'उत्पाद',
                legal: 'कानूनी',
                privacy: 'गोपनीयता नीति',
                terms: 'सेवा की शर्तें',
                disclaimer: 'अस्वीकरण',
                rights: 'सर्वाधिकार सुरक्षित।',
                madeWith: 'भारत के लिए ❤️ के साथ बनाया गया',
            },
        },
        dashboard: {
            title: 'डैशबोर्ड',
            welcome: 'वापसी पर स्वागत है,',
            subtitle: "यहाँ आपके कानूनी दस्तावेजों के साथ क्या हो रहा है।",
            newAnalysis: 'नया विश्लेषण',
            stats: {
                documents: 'दस्तावेज़ विश्लेषण',
                time: 'समय की बचत',
                score: 'कानूनी स्कोर',
            },
            recentActivity: {
                title: 'हाल की गतिविधि',
                viewAll: 'सभी देखें',
            },
            quickActions: {
                title: 'त्वरित कार्रवाई',
                upload: 'दस्तावेज़ अपलोड करें',
                findLawyer: 'वकील खोजें',
                updateProfile: 'प्रोफ़ाइल अपडेट करें',
            },
        },
        upload: {
            title: 'दस्तावेज़ अपलोड करें',
            subtitle: 'शुरू करने के लिए एक कानूनी दस्तावेज़ (पीडीएफ) अपलोड करें।',
            dragDrop: 'अपनी पीडीएफ यहां खींचें और छोड़ें',
            browse: 'या फ़ाइलों को ब्राउज़ करने के लिए क्लिक करें',
            selectFile: 'फ़ाइल चुनें',
            process: 'दस्तावेज़ प्रक्रिया करें',
            extracting: 'पाठ निकाला जा रहा है...',
        },
        legalAid: {
            title: 'कानूनी सहायता खोजें',
            subtitle: 'अपने पास अनुभवी वकीलों और कानूनी सहायता स्वयंसेवकों से जुड़ें',
            searchPlaceholder: 'नाम या विशेषज्ञता के आधार पर खोजें...',
            selectLocation: 'अपना स्थान चुनें',
            allCities: 'सभी शहर',
            selectSpecialization: 'विशेषज्ञता चुनें',
            allSpecializations: 'सभी विशेषज्ञताएं',
            found: 'मिला',
            providers: 'कानूनी सहायता प्रदाता',
            call: 'कॉल करें',
            email: 'ईमेल करें',
            experience: 'अनुभव',
            languages: 'भाषाएं',
            availability: 'उपलब्धता',
            noResults: 'आपके मानदंडों से मेल खाने वाले कोई कानूनी सहायता प्रदाता नहीं मिले।',
            clearFilters: 'फ़िल्टर साफ़ करें',
        },
        account: {
            title: 'मेरा खाता',
            subtitle: 'अपनी प्रोफ़ाइल सेटिंग्स प्रबंधित करें',
            editProfile: 'प्रोफ़ाइल संपादित करें',
            cancel: 'रद्द करें',
            firstName: 'पहला नाम',
            lastName: 'अंतिम नाम',
            emailAddress: 'ईमेल पता',
            emailCannotChange: 'ईमेल बदला नहीं जा सकता।',
            saveChanges: 'परिवर्तन सहेजें',
            freePlan: 'मुक्त योजना',
            updateSuccess: 'प्रोफ़ाइल सफलतापूर्वक अपडेट किया गया!',
            updateFailed: 'प्रोफ़ाइल अपडेट करने में विफल।',
        },
        login: {
            title: 'वापसी पर स्वागत है',
            subtitle: 'अपने कोडबंधु खाते में साइन इन करें',
            email: 'ईमेल पता',
            password: 'पासवर्ड',
            rememberMe: 'मुझे याद रखें',
            forgotPassword: 'पासवर्ड भूल गए?',
            signIn: 'साइन इन करें',
            signingIn: 'साइन इन हो रहा है...',
            noAccount: "खाता नहीं है?",
            createAccount: 'खाता बनाएं',
            demoCredentials: 'डेमो क्रेडेंशियल्स:',
        },
        signup: {
            title: 'खाता बनाएं',
            subtitle: 'आज ही कोडबंधु से जुड़ें',
            firstName: 'पहला नाम',
            lastName: 'अंतिम नाम',
            email: 'ईमेल पता',
            password: 'पासवर्ड',
            createAccount: 'खाता बनाएं',
            creating: 'खाता बनाया जा रहा है...',
            hasAccount: 'क्या आपके पास पहले से एक खाता है?',
            signIn: 'साइन इन करें',
        },
        documents: {
            title: 'मेरे दस्तावेज़',
            empty: 'कोई दस्तावेज़ नहीं मिले।',
            headers: {
                name: 'दस्तावेज़ का नाम',
                date: 'तारीख',
                type: 'प्रकार',
                status: 'स्थिति',
                actions: 'कार्रवाई',
            },
        },
        processing: {
            title: 'दस्तावेज़ का विश्लेषण',
            step1: 'दस्तावेज़ संरचना स्कैन की जा रही है...',
            step2: 'कानूनी धाराओं की पहचान की जा रही है...',
            step3: 'जटिल भाषा को सरल बनाया जा रहा है...',
            step4: 'सारांश तैयार किया जा रहा है...',
            step5: 'सलाह तैयार की जा रही है...',
            complete: 'विश्लेषण पूर्ण!',
        },
        results: {
            title: 'विश्लेषण परिणाम',
            back: 'डैशबोर्ड पर वापस जाएं',
            tabs: {
                simplification: 'सरलीकरण',
                summary: 'सारांश',
                advisory: 'कानूनी सलाह',
                chat: 'एआई से पूछें',
            },
            simplification: {
                original: 'मूल पाठ',
                simplified: 'सरलीकृत संस्करण',
            },
            summary: {
                issue: 'कानूनी मुद्दा',
                facts: 'प्रमुख तथ्य',
                arguments: 'तर्क',
                conclusion: 'निष्कर्ष',
            },
            advisory: {
                rights: 'आपके अधिकार',
                actions: 'अनुशंसित कार्रवाई',
                risk: 'जोखिम मूल्यांकन',
            },
        },
    },
    pa: {
        nav: {
            upload: 'ਦਸਤਾਵੇਜ਼ ਅੱਪਲੋਡ ਕਰੋ',
            documents: 'ਮੇਰੇ ਦਸਤਾਵੇਜ਼',
            settings: 'ਸੈਟਿੰਗਜ਼',
            legalAid: 'ਕਾਨੂੰਨੀ ਸਹਾਇਤਾ',
            signout: 'ਸਾਈਨ ਆਉਟ',
            features: 'ਵਿਸ਼ੇਸ਼ਤਾਵਾਂ',
            howItWorks: 'ਇਹ ਕਿਵੇਂ ਕੰਮ ਕਰਦਾ ਹੈ',
            testimonials: 'ਪ੍ਰਸ਼ੰਸਾ ਪੱਤਰ',
            signIn: 'ਸਾਈਨ ਇਨ',
            getStarted: 'ਸ਼ੁਰੂ ਕਰੋ',
        },
        landing: {
            hero: {
                badge: 'AI-ਸੰਚਾਲਿਤ ਕਾਨੂੰਨੀ ਸਹਾਇਕ 2.0',
                title: 'ਕਾਨੂੰਨੀ ਬੁੱਧੀ',
                subtitle: 'ਸਾਰਿਆਂ ਲਈ ਮੁੜ ਕਲਪਨਾ',
                description: 'ਗੁੰਝਲਦਾਰ ਕਾਨੂੰਨੀ ਦਸਤਾਵੇਜ਼ਾਂ ਨੂੰ ਸਰਲ ਬਣਾਓ, ਤੁਰੰਤ ਸਲਾਹ ਪ੍ਰਾਪਤ ਕਰੋ, ਅਤੇ ਉੱਨਤ AI ਦੀ ਸ਼ਕਤੀ ਨਾਲ ਕਾਨੂੰਨੀ ਸਹਾਇਤਾ ਲੱਭੋ। ਸੁਰੱਖਿਅਤ, ਤੇਜ਼ ਅਤੇ ਪਹੁੰਚਯੋਗ।',
                startFree: 'ਮੁਫ਼ਤ ਸ਼ੁਰੂ ਕਰੋ',
                liveDemo: 'ਲਾਈਵ ਡੈਮੋ',
            },
            features: {
                title: 'ਕੋਡਬੰਧੂ ਕਿਉਂ ਚੁਣੋ?',
                subtitle: 'ਭਾਰਤੀ ਕਾਨੂੰਨੀ ਢਾਂਚੇ ਲਈ ਨਾਗਰਿਕਾਂ, ਵਿਦਿਆਰਥੀਆਂ ਅਤੇ ਪੇਸ਼ੇਵਰਾਂ ਦੀ ਮਦਦ ਲਈ ਵਿਸ਼ੇਸ਼ ਤੌਰ ਤੇ ਬਣਾਇਆ ਗਿਆ।',
                simplification: {
                    title: 'ਤੁਰੰਤ ਸਰਲਤਾ',
                    desc: 'ਸਾਡੇ ਲੀਗਲ-ਬਰਟ ਸੰਚਾਲਿਤ ਇੰਜਣ ਦੀ ਵਰਤੋਂ ਕਰਕੇ ਗੁੰਝਲਦਾਰ ਕਾਨੂੰਨੀ ਭਾਸ਼ਾ ਦਾ ਸਰਲ ਅੰਗਰੇਜ਼ੀ (ਅਤੇ ਜਲਦੀ ਹੀ ਹਿੰਦੀ) ਵਿੱਚ ਅਨੁਵਾਦ ਕਰੋ।',
                },
                summarization: {
                    title: 'ਸਮਾਰਟ ਸੰਖੇਪ',
                    desc: 'ਸੰਖੇਪ ਸਾਰਾਂਸ਼ ਪ੍ਰਾਪਤ ਕਰੋ ਜੋ ਆਪਣੇ ਆਪ ਮੁੱਦੇ, ਤੱਥਾਂ, ਦਲੀਲਾਂ ਅਤੇ ਸਿੱਟਿਆਂ ਨੂੰ ਉਜਾਗਰ ਕਰਦੇ ਹਨ।',
                },
                advisory: {
                    title: 'ਕਾਰਵਾਈਯੋਗ ਸਲਾਹ',
                    desc: 'ਅੱਗੇ ਕੀ ਕਦਮ ਚੁੱਕਣੇ ਹਨ (ਜਿਵੇਂ ਕਿ RTI, FIR, ਸ਼ਿਕਾਇਤ) ਤੇ ਗੈਰ-ਬਾਈਡਿੰਗ ਕਾਨੂੰਨੀ ਸੁਝਾਅ ਪ੍ਰਾਪਤ ਕਰੋ।',
                },
            },
            howItWorks: {
                title: 'ਇਹ ਕਿਵੇਂ ਕੰਮ ਕਰਦਾ ਹੈ',
                subtitle: '3 ਆਸਾਨ ਕਦਮਾਂ ਵਿੱਚ ਆਪਣੇ ਕਾਨੂੰਨੀ ਜਵਾਬ ਪ੍ਰਾਪਤ ਕਰੋ।',
                step1: { title: 'ਦਸਤਾਵੇਜ਼ ਅੱਪਲੋਡ ਕਰੋ', desc: 'ਆਪਣਾ ਕਾਨੂੰਨੀ ਨੋਟਿਸ, ਇਕਰਾਰਨਾਮਾ, ਜਾਂ ਸਵਾਲ ਸੁਰੱਖਿਅਤ ਢੰਗ ਨਾਲ ਅੱਪਲੋਡ ਕਰੋ।' },
                step2: { title: 'AI ਵਿਸ਼ਲੇਸ਼ਣ', desc: 'ਸਾਡਾ AI ਸਮੱਗਰੀ ਨੂੰ ਤੁਰੰਤ ਸਕੈਨ, ਸਰਲ ਅਤੇ ਸੰਖੇਪ ਕਰਦਾ ਹੈ।' },
                step3: { title: 'ਨਤੀਜੇ ਪ੍ਰਾਪਤ ਕਰੋ', desc: 'ਇੱਕ ਸਧਾਰਨ ਅੰਗਰੇਜ਼ੀ ਸਾਰਾਂਸ਼ ਅਤੇ ਕਾਰਵਾਈਯੋਗ ਸਲਾਹ ਪ੍ਰਾਪਤ ਕਰੋ।' },
            },
            testimonials: {
                title: 'ਹਜ਼ਾਰਾਂ ਦੁਆਰਾ ਭਰੋਸੇਯੋਗ',
                subtitle: 'ਦੇਖੋ ਕਿ ਸਾਡੇ ਉਪਭੋਗਤਾ ਕੋਡਬੰਧੂ ਬਾਰੇ ਕੀ ਕਹਿ ਰਹੇ ਹਨ।',
            },
            about: {
                mission: 'ਸਾਡਾ ਮਿਸ਼ਨ',
                title: 'ਕਾਨੂੰਨੀ ਪਾੜੇ ਨੂੰ ਪੂਰਾ ਕਰਨਾ',
                desc1: 'ਭਾਰਤ ਵਿੱਚ, ਲੱਖਾਂ ਨਾਗਰਿਕ ਗੁੰਝਲਦਾਰ ਭਾਸ਼ਾ ਅਤੇ ਪਹੁੰਚਯੋਗ ਸਰੋਤਾਂ ਦੀ ਘਾਟ ਕਾਰਨ ਆਪਣੇ ਕਾਨੂੰਨੀ ਅਧਿਕਾਰਾਂ ਨੂੰ ਸਮਝਣ ਲਈ ਸੰਘਰਸ਼ ਕਰਦੇ ਹਨ।',
                desc2: 'ਕੋਡਬੰਧੂ ਇੱਕ AI-ਸੰਚਾਲਿਤ ਪਹਿਲਕਦਮੀ ਹੈ ਜਿਸਨੂੰ ਕਾਨੂੰਨੀ ਪਹੁੰਚ ਨੂੰ ਲੋਕਤੰਤਰੀਕਰਨ ਲਈ ਤਿਆਰ ਕੀਤਾ ਗਿਆ ਹੈ। ਅਸੀਂ ਨਿਆਂ ਨੂੰ ਸਾਰਿਆਂ ਲਈ ਪਹੁੰਚਯੋਗ ਬਣਾਉਣ ਲਈ ਅਤਿ-ਆਧੁਨਿਕ ਕੁਦਰਤੀ ਭਾਸ਼ਾ ਪ੍ਰੋਸੈਸਿੰਗ (NLP) ਨੂੰ ਡੂੰਘੀ ਕਾਨੂੰਨੀ ਮੁਹਾਰਤ ਨਾਲ ਜੋੜਦੇ ਹਨ।',
                stats: { accuracy: 'ਸ਼ੁੱਧਤਾ ਦਰ', availability: 'ਉਪਲਬਧਤਾ' },
                citizens: { title: 'ਨਾਗਰਿਕਾਂ ਲਈ', desc: 'ਸਰਲ ਭਾਸ਼ਾ ਵਿੱਚ ਇਕਰਾਰਨਾਮੇ, ਨੋਟਿਸ ਅਤੇ ਅਧਿਕਾਰਾਂ ਨੂੰ ਸਮਝੋ।' },
                legalAid: { title: 'ਕਾਨੂੰਨੀ ਸਹਾਇਤਾ ਲਈ', desc: 'ਕੇਸ ਪ੍ਰਕਿਰਿਆ ਅਤੇ ਦਸਤਾਵੇਜ਼ ਸਮੀਖਿਆ ਵਿੱਚ ਤੇਜ਼ੀ ਲਿਆਓ।' },
                ngos: { title: 'NGOs ਲਈ', desc: 'ਤੁਰੰਤ ਕਾਨੂੰਨੀ ਸਾਖਰਤਾ ਸਾਧਨਾਂ ਨਾਲ ਭਾਈਚਾਰਿਆਂ ਨੂੰ ਸ਼ਕਤੀਸ਼ਾਲੀ ਬਣਾਓ।' },
            },
            contact: {
                title: 'ਸੰਪਰਕ ਕਰੋ',
                subtitle: 'ਕੋਡਬੰਧੂ ਬਾਰੇ ਸਵਾਲ ਹਨ? ਸਾਡੀ ਟੀਮ ਪਲੇਟਫਾਰਮ ਨੂੰ ਨੈਵੀਗੇਟ ਕਰਨ ਵਿੱਚ ਤੁਹਾਡੀ ਮਦਦ ਕਰਨ ਲਈ ਇੱਥੇ ਹੈ।',
                firstName: 'ਪਹਿਲਾ ਨਾਮ',
                lastName: 'ਆਖਰੀ ਨਾਮ',
                email: 'ਈਮੇਲ ਪਤਾ',
                message: 'ਸੁਨੇਹਾ',
                send: 'ਸੁਨੇਹਾ ਭੇਜੋ',
            },
            footer: {
                desc: 'AI ਦੀ ਸ਼ਕਤੀ ਰਾਹੀਂ ਭਾਰਤੀ ਕਾਨੂੰਨ ਨੂੰ ਸਾਰਿਆਂ ਲਈ ਸਰਲ, ਪਹੁੰਚਯੋਗ ਅਤੇ ਸਮਝਣਯੋਗ ਬਣਾਉਣਾ।',
                product: 'ਉਤਪਾਦ',
                legal: 'ਕਾਨੂੰਨੀ',
                privacy: 'ਪਰਦੇਦਾਰੀ ਨੀਤੀ',
                terms: 'ਸੇਵਾ ਦੀਆਂ ਸ਼ਰਤਾਂ',
                disclaimer: 'ਬੇਦਾਅਵਾ',
                rights: 'ਸਾਰੇ ਹੱਕ ਰਾਖਵੇਂ ਹਨ।',
                madeWith: 'ਭਾਰਤ ਲਈ ❤️ ਨਾਲ ਬਣਾਇਆ ਗਿਆ',
            },
        },
        dashboard: {
            title: 'ਡੈਸ਼ਬੋਰਡ',
            welcome: 'ਵਾਪਸੀ ਤੇ ਜੀ ਆਇਆਂ ਨੂੰ,',
            subtitle: "ਇੱਥੇ ਤੁਹਾਡੇ ਕਾਨੂੰਨੀ ਦਸਤਾਵੇਜ਼ਾਂ ਨਾਲ ਕੀ ਹੋ ਰਿਹਾ ਹੈ।",
            newAnalysis: 'ਨਵਾਂ ਵਿਸ਼ਲੇਸ਼ਣ',
            stats: {
                documents: 'ਦਸਤਾਵੇਜ਼ ਵਿਸ਼ਲੇਸ਼ਣ',
                time: 'ਸਮੇਂ ਦੀ ਬੱਚਤ',
                score: 'ਕਾਨੂੰਨੀ ਸਕੋਰ',
            },
            recentActivity: {
                title: 'ਹਾਲੀਆ ਗਤੀਵਿਧੀ',
                viewAll: 'ਸਭ ਦੇਖੋ',
            },
            quickActions: {
                title: 'ਤੁਰੰਤ ਕਾਰਵਾਈ',
                upload: 'ਦਸਤਾਵੇਜ਼ ਅੱਪਲੋਡ ਕਰੋ',
                findLawyer: 'ਵਕੀਲ ਲੱਭੋ',
                updateProfile: 'ਪ੍ਰੋਫਾਈਲ ਅੱਪਡੇਟ ਕਰੋ',
            },
        },
        upload: {
            title: 'ਦਸਤਾਵੇਜ਼ ਅੱਪਲੋਡ ਕਰੋ',
            subtitle: 'ਸ਼ੁਰੂ ਕਰਨ ਲਈ ਇੱਕ ਕਾਨੂੰਨੀ ਦਸਤਾਵੇਜ਼ (PDF) ਅੱਪਲੋਡ ਕਰੋ।',
            dragDrop: 'ਆਪਣੀ PDF ਇੱਥੇ ਖਿੱਚੋ ਅਤੇ ਛੱਡੋ',
            browse: 'ਜਾਂ ਫਾਈਲਾਂ ਬ੍ਰਾਊਜ਼ ਕਰਨ ਲਈ ਕਲਿੱਕ ਕਰੋ',
            selectFile: 'ਫਾਈਲ ਚੁਣੋ',
            process: 'ਦਸਤਾਵੇਜ਼ ਪ੍ਰਕਿਰਿਆ ਕਰੋ',
            extracting: 'ਟੈਕਸਟ ਕੱਢਿਆ ਜਾ ਰਿਹਾ ਹੈ...',
        },
        legalAid: {
            title: 'ਕਾਨੂੰਨੀ ਸਹਾਇਤਾ ਲੱਭੋ',
            subtitle: 'ਆਪਣੇ ਨੇੜੇ ਤਜਰਬੇਕਾਰ ਵਕੀਲਾਂ ਅਤੇ ਕਾਨੂੰਨੀ ਸਹਾਇਤਾ ਵਲੰਟੀਅਰਾਂ ਨਾਲ ਜੁੜੋ',
            searchPlaceholder: 'ਨਾਮ ਜਾਂ ਮਾਹਰਤਾ ਦੁਆਰਾ ਖੋਜੋ...',
            selectLocation: 'ਆਪਣਾ ਸਥਾਨ ਚੁਣੋ',
            allCities: 'ਸਾਰੇ ਸ਼ਹਿਰ',
            selectSpecialization: 'ਮਾਹਰਤਾ ਚੁਣੋ',
            allSpecializations: 'ਸਾਰੀਆਂ ਮਾਹਰਤਾਵਾਂ',
            found: 'ਮਿਲੇ',
            providers: 'ਕਾਨੂੰਨੀ ਸਹਾਇਤਾ ਪ੍ਰਦਾਤਾ',
            call: 'ਕਾਲ ਕਰੋ',
            email: 'ਈਮੇਲ ਕਰੋ',
            experience: 'ਤਜਰਬਾ',
            languages: 'ਭਾਸ਼ਾਵਾਂ',
            availability: 'ਉਪਲਬਧਤਾ',
            noResults: 'ਤੁਹਾਡੇ ਮਾਪਦੰਡ ਨਾਲ ਮੇਲ ਖਾਂਦੇ ਕੋਈ ਕਾਨੂੰਨੀ ਸਹਾਇਤਾ ਪ੍ਰਦਾਤਾ ਨਹੀਂ ਮਿਲੇ।',
            clearFilters: 'ਫਿਲਟਰ ਸਾਫ਼ ਕਰੋ',
        },
        account: {
            title: 'ਮੇਰਾ ਖਾਤਾ',
            subtitle: 'ਆਪਣੇ ਪ੍ਰੋਫਾਈਲ ਸੈਟਿੰਗਜ਼ ਦਾ ਪ੍ਰਬੰਧਨ ਕਰੋ',
            editProfile: 'ਪ੍ਰੋਫਾਈਲ ਸੰਪਾਦਿਤ ਕਰੋ',
            cancel: 'ਰੱਦ ਕਰੋ',
            firstName: 'ਪਹਿਲਾ ਨਾਮ',
            lastName: 'ਆਖਰੀ ਨਾਮ',
            emailAddress: 'ਈਮੇਲ ਪਤਾ',
            emailCannotChange: 'ਈਮੇਲ ਬਦਲੀ ਨਹੀਂ ਜਾ ਸਕਦੀ।',
            saveChanges: 'ਤਬਦੀਲੀਆਂ ਸੁਰੱਖਿਅਤ ਕਰੋ',
            freePlan: 'ਮੁਫ਼ਤ ਯੋਜਨਾ',
            updateSuccess: 'ਪ੍ਰੋਫਾਈਲ ਸਫਲਤਾਪੂਰਵਕ ਅੱਪਡੇਟ ਕੀਤਾ ਗਿਆ!',
            updateFailed: 'ਪ੍ਰੋਫਾਈਲ ਅੱਪਡੇਟ ਕਰਨ ਵਿੱਚ ਅਸਫਲ।',
        },
        login: {
            title: 'ਵਾਪਸੀ ਤੇ ਜੀ ਆਇਆਂ ਨੂੰ',
            subtitle: 'ਆਪਣੇ ਕੋਡਬੰਧੂ ਖਾਤੇ ਵਿੱਚ ਸਾਈਨ ਇਨ ਕਰੋ',
            email: 'ਈਮੇਲ ਪਤਾ',
            password: 'ਪਾਸਵਰਡ',
            rememberMe: 'ਮੈਨੂੰ ਯਾਦ ਰੱਖੋ',
            forgotPassword: 'ਪਾਸਵਰਡ ਭੁੱਲ ਗਏ?',
            signIn: 'ਸਾਈਨ ਇਨ',
            signingIn: 'ਸਾਈਨ ਇਨ ਹੋ ਰਿਹਾ ਹੈ...',
            noAccount: "ਖਾਤਾ ਨਹੀਂ ਹੈ?",
            createAccount: 'ਖਾਤਾ ਬਣਾਓ',
            demoCredentials: 'ਡੈਮੋ ਵੇਰਵੇ:',
        },
        signup: {
            title: 'ਖਾਤਾ ਬਣਾਓ',
            subtitle: 'ਅੱਜ ਹੀ ਕੋਡਬੰਧੂ ਨਾਲ ਜੁੜੋ',
            firstName: 'ਪਹਿਲਾ ਨਾਮ',
            lastName: 'ਆਖਰੀ ਨਾਮ',
            email: 'ਈਮੇਲ ਪਤਾ',
            password: 'ਪਾਸਵਰਡ',
            createAccount: 'ਖਾਤਾ ਬਣਾਓ',
            creating: 'ਖਾਤਾ ਬਣਾਇਆ ਜਾ ਰਿਹਾ ਹੈ...',
            hasAccount: 'ਕੀ ਤੁਹਾਡੇ ਕੋਲ ਪਹਿਲਾਂ ਹੀ ਇੱਕ ਖਾਤਾ ਹੈ?',
            signIn: 'ਸਾਈਨ ਇਨ',
        },
        documents: {
            title: 'ਮੇਰੇ ਦਸਤਾਵੇਜ਼',
            empty: 'ਕੋਈ ਦਸਤਾਵੇਜ਼ ਨਹੀਂ ਮਿਲੇ।',
            headers: {
                name: 'ਦਸਤਾਵੇਜ਼ ਦਾ ਨਾਮ',
                date: 'ਮਿਤੀ',
                type: 'ਕਿਸਮ',
                status: 'ਸਥਿਤੀ',
                actions: 'ਕਾਰਵਾਈ',
            },
        },
        processing: {
            title: 'ਦਸਤਾਵੇਜ਼ ਦਾ ਵਿਸ਼ਲੇਸ਼ਣ',
            step1: 'ਦਸਤਾਵੇਜ਼ ਢਾਂਚੇ ਨੂੰ ਸਕੈਨ ਕੀਤਾ ਜਾ ਰਿਹਾ ਹੈ...',
            step2: 'ਕਾਨੂੰਨੀ ਧਾਰਾਵਾਂ ਦੀ ਪਛਾਣ ਕੀਤੀ ਜਾ ਰਹੀ ਹੈ...',
            step3: 'ਗੁੰਝਲਦਾਰ ਭਾਸ਼ਾ ਨੂੰ ਸਰਲ ਬਣਾਇਆ ਜਾ ਰਿਹਾ ਹੈ...',
            step4: 'ਸਾਰਾਂਸ਼ ਤਿਆਰ ਕੀਤਾ ਜਾ ਰਿਹਾ ਹੈ...',
            step5: 'ਸਲਾਹ ਤਿਆਰ ਕੀਤੀ ਜਾ ਰਹੀ ਹੈ...',
            complete: 'ਵਿਸ਼ਲੇਸ਼ਣ ਪੂਰਾ!',
        },
        results: {
            title: 'ਵਿਸ਼ਲੇਸ਼ਣ ਨਤੀਜੇ',
            back: 'ਡੈਸ਼ਬੋਰਡ ਤੇ ਵਾਪਸ ਜਾਓ',
            tabs: {
                simplification: 'ਸਰਲੀਕਰਨ',
                summary: 'ਸਾਰਾਂਸ਼',
                advisory: 'ਕਾਨੂੰਨੀ ਸਲਾਹ',
                chat: 'AI ਨੂੰ ਪੁੱਛੋ',
            },
            simplification: {
                original: 'ਅਸਲ ਪਾਠ',
                simplified: 'ਸਰਲ ਸੰਸਕਰਣ',
            },
            summary: {
                issue: 'ਕਾਨੂੰਨੀ ਮੁੱਦਾ',
                facts: 'ਮੁੱਖ ਤੱਥ',
                arguments: 'ਦਲੀਲਾਂ',
                conclusion: 'ਸਿੱਟਾ',
            },
            advisory: {
                rights: 'ਤੁਹਾਡੇ ਅਧਿਕਾਰ',
                actions: 'ਸਿਫਾਰਸ਼ ਕੀਤੀਆਂ ਕਾਰਵਾਈਆਂ',
                risk: 'ਜੋਖਮ ਮੁਲਾਂਕਣ',
            },
        },
    },
    ta: {
        nav: {
            upload: 'ஆவணத்தை பதிவேற்றவும்',
            documents: 'எனது ஆவணங்கள்',
            settings: 'அமைப்புகள்',
            legalAid: 'சட்ட உதவி',
            signout: 'வெளியேறு',
            features: 'அம்சங்கள்',
            howItWorks: 'எப்படி வேலை செய்கிறது',
            testimonials: 'சான்றுகள்',
            signIn: 'உள்நுழைய',
            getStarted: 'தொடங்குங்கள்',
        },
        landing: {
            hero: {
                badge: 'AI-இயங்கும் சட்ட உதவியாளர் 2.0',
                title: 'சட்ட நுண்ணறிவு',
                subtitle: 'அனைவருக்கும் மறுவடிவமைப்பு',
                description: 'சிக்கலான சட்ட ஆவணங்களை எளிதாக்குங்கள், உடனடி ஆலோசனையைப் பெறுங்கள் மற்றும் மேம்பட்ட AI இன் சக்தியுடன் சட்ட உதவியைக் கண்டறியவும். பாதுகாப்பான, வேகமான மற்றும் அணுகக்கூடிய.',
                startFree: 'இலவசமாகத் தொடங்குங்கள்',
                liveDemo: 'நேரடி டெமோ',
            },
            features: {
                title: 'கோட்பந்துவை ஏன் தேர்வு செய்ய வேண்டும்?',
                subtitle: 'குடிமக்கள், மாணவர்கள் மற்றும் தொழில் வல்லுநர்களுக்கு உதவ இந்திய சட்ட கட்டமைப்பிற்காக குறிப்பாக உருவாக்கப்பட்டது.',
                simplification: {
                    title: 'உடனடி எளிமைப்படுத்தல்',
                    desc: 'எங்கள் Legal-BERT இயங்கும் இயந்திரத்தைப் பயன்படுத்தி சிக்கலான சட்ட மொழியை எளிய ஆங்கிலத்தில் (மற்றும் விரைவில் இந்தியில்) மொழிபெயர்க்கவும்.',
                },
                summarization: {
                    title: 'ஸ்மார்ட் சுருக்கம்',
                    desc: 'சிக்கல், உண்மைகள், வாதங்கள் மற்றும் முடிவுகளை தானாகவே முன்னிலைப்படுத்தும் சுருக்கமான சுருக்கங்களைப் பெறுங்கள்.',
                },
                advisory: {
                    title: 'செயல்படக்கூடிய ஆலோசனை',
                    desc: 'அடுத்து என்ன நடவடிக்கைகளை எடுக்க வேண்டும் (எ.கா., RTI, FIR, குறைதீர்வு) என்பது குறித்த பிணைக்காத சட்ட பரிந்துரைகளைப் பெறுங்கள்.',
                },
            },
            howItWorks: {
                title: 'எப்படி வேலை செய்கிறது',
                subtitle: '3 எளிய படிகளில் உங்கள் சட்ட பதில்களைப் பெறுங்கள்.',
                step1: { title: 'ஆவணத்தை பதிவேற்றவும்', desc: 'உங்கள் சட்ட அறிவிப்பு, ஒப்பந்தம் அல்லது கேள்வியை பாதுகாப்பாக பதிவேற்றவும்.' },
                step2: { title: 'AI பகுப்பாய்வு', desc: 'எங்கள் AI உள்ளடக்கத்தை உடனடியாக ஸ்கேன் செய்து, எளிதாக்கி, சுருக்கமாகக் கூறுகிறது.' },
                step3: { title: 'முடிவுகளைப் பெறுங்கள்', desc: 'எளிய ஆங்கில சுருக்கம் மற்றும் செயல்படக்கூடிய ஆலோசனையைப் பெறுங்கள்.' },
            },
            testimonials: {
                title: 'ஆயிரக்கணக்கானோரால் நம்பப்படுகிறது',
                subtitle: 'எங்கள் பயனர்கள் கோட்பந்து பற்றி என்ன சொல்கிறார்கள் என்பதைப் பாருங்கள்.',
            },
            about: {
                mission: 'எங்கள் நோக்கம்',
                title: 'சட்ட இடைவெளியைக் குறைத்தல்',
                desc1: 'இந்தியாவில், சிக்கலான மொழி மற்றும் அணுகக்கூடிய வளங்கள் இல்லாததால் மில்லியன் கணக்கான குடிமக்கள் தங்கள் சட்ட உரிமைகளைப் புரிந்து கொள்ள சிரமப்படுகிறார்கள்.',
                desc2: 'கோட்பந்து என்பது சட்ட அணுகலை ஜனநாயகப்படுத்த வடிவமைக்கப்பட்ட ஒரு AI-இயங்கும் முயற்சியாகும். கிராமப்புற குடிமக்கள் முதல் நகர்ப்புற தொழில் வல்லுநர்கள் வரை அனைவருக்கும் நீதியை அணுகக்கூடியதாக மாற்ற அதிநவீன இயற்கை மொழி செயலாக்கத்தை (NLP) ஆழ்ந்த சட்ட நிபுணத்துவத்துடன் இணைக்கிறோம்.',
                stats: { accuracy: 'துல்லிய விகிதம்', availability: 'கிடைக்கும் தன்மை' },
                citizens: { title: 'குடிமக்களுக்கு', desc: 'ஒப்பந்தங்கள், அறிவிப்புகள் மற்றும் உரிமைகளை எளிய மொழியில் புரிந்து கொள்ளுங்கள்.' },
                legalAid: { title: 'சட்ட உதவிக்கு', desc: 'வழக்கு செயலாக்கம் மற்றும் ஆவண மதிப்பாய்வை விரைவுபடுத்துங்கள்.' },
                ngos: { title: 'தன்னார்வ தொண்டு நிறுவனங்களுக்கு', desc: 'உடனடி சட்ட எழுத்தறிவு கருவிகளுடன் சமூகங்களை மேம்படுத்துங்கள்.' },
            },
            contact: {
                title: 'தொடர்பு கொள்ள',
                subtitle: 'கோட்பந்து பற்றி கேள்விகள் உள்ளதா? தளத்தை வழிநடத்த எங்கள் குழு உங்களுக்கு உதவ இங்கே உள்ளது.',
                firstName: 'முதல் பெயர்',
                lastName: 'கடைசி பெயர்',
                email: 'மின்னஞ்சல் முகவரி',
                message: 'செய்தி',
                send: 'செய்தி அனுப்பு',
            },
            footer: {
                desc: 'AI இன் சக்தி மூலம் இந்திய சட்டத்தை அனைவருக்கும் எளிமையான, அணுகக்கூடிய மற்றும் புரிந்து கொள்ளக்கூடியதாக மாற்றுதல்.',
                product: 'தயாரிப்பு',
                legal: 'சட்டம்',
                privacy: 'தனியுரிமைக் கொள்கை',
                terms: 'சேவை விதிமுறைகள்',
                disclaimer: 'மறுப்பு',
                rights: 'அனைத்து உரிமைகளும் பாதுகாக்கப்பட்டவை.',
                madeWith: 'இந்தியாவிற்காக ❤️ உடன் உருவாக்கப்பட்டது',
            },
        },
        dashboard: {
            title: 'முகப்பு',
            welcome: 'மீண்டும் வருக,',
            subtitle: "உங்கள் சட்ட ஆவணங்களுடன் என்ன நடக்கிறது என்பது இங்கே.",
            newAnalysis: 'புதிய பகுப்பாய்வு',
            stats: {
                documents: 'ஆவணங்கள் பகுப்பாய்வு',
                time: 'நேரம் சேமிக்கப்பட்டது',
                score: 'சட்ட மதிப்பெண்',
            },
            recentActivity: {
                title: 'சமீபத்திய செயல்பாடு',
                viewAll: 'அனைத்தையும் காண்க',
            },
            quickActions: {
                title: 'விரைவான செயல்கள்',
                upload: 'ஆவணத்தை பதிவேற்றவும்',
                findLawyer: 'வழக்கறிஞரைக் கண்டறியவும்',
                updateProfile: 'சுயவிவரத்தைப் புதுப்பிக்கவும்',
            },
        },
        upload: {
            title: 'ஆவணத்தை பதிவேற்றவும்',
            subtitle: 'தொடங்க ஒரு சட்ட ஆவணத்தை (PDF) பதிவேற்றவும்.',
            dragDrop: 'உங்கள் PDF ஐ இங்கே இழுத்து விடவும்',
            browse: 'அல்லது கோப்புகளை உலாவ கிளிக் செய்யவும்',
            selectFile: 'கோப்பைத் தேர்ந்தெடுக்கவும்',
            process: 'ஆவணத்தை செயலாக்கவும்',
            extracting: 'உரை பிரித்தெடுக்கப்படுகிறது...',
        },
        legalAid: {
            title: 'சட்ட உதவியைக் கண்டறியவும்',
            subtitle: 'உங்களுக்கு அருகிலுள்ள அனுபவம் வாய்ந்த வழக்கறிஞர்கள் மற்றும் சட்ட உதவி தன்னார்வலர்களுடன் இணையுங்கள்',
            searchPlaceholder: 'பெயர் அல்லது நிபுணத்துவம் மூலம் தேடவும்...',
            selectLocation: 'உங்கள் இருப்பிடத்தைத் தேர்ந்தெடுக்கவும்',
            allCities: 'அனைத்து நகரங்களும்',
            selectSpecialization: 'நிபுணத்துவத்தைத் தேர்ந்தெடுக்கவும்',
            allSpecializations: 'அனைத்து நிபுணத்துவங்களும்',
            found: 'கண்டறியப்பட்டது',
            providers: 'சட்ட உதவி வழங்குநர்கள்',
            call: 'அழைக்கவும்',
            email: 'மின்னஞ்சல்',
            experience: 'அனுபவம்',
            languages: 'மொழிகள்',
            availability: 'கிடைக்கும் தன்மை',
            noResults: 'உங்கள் அளவுகோல்களுடன் பொருந்தக்கூடிய சட்ட உதவி வழங்குநர்கள் எதுவும் இல்லை.',
            clearFilters: 'வடிப்பான்களை அழிக்கவும்',
        },
        account: {
            title: 'எனது கணக்கு',
            subtitle: 'உங்கள் சுயவிவர அமைப்புகளை நிர்வகிக்கவும்',
            editProfile: 'சுயவிவரத்தைத் திருத்தவும்',
            cancel: 'ரத்துசெய்',
            firstName: 'முதல் பெயர்',
            lastName: 'கடைசி பெயர்',
            emailAddress: 'மின்னஞ்சல் முகவரி',
            emailCannotChange: 'மின்னஞ்சலை மாற்ற முடியாது.',
            saveChanges: 'மாற்றங்களைச் சேமிக்கவும்',
            freePlan: 'இலவச திட்டம்',
            updateSuccess: 'சுயவிவரம் வெற்றிகரமாக புதுப்பிக்கப்பட்டது!',
            updateFailed: 'சுயவிவரத்தைப் புதுப்பிக்க முடியவில்லை.',
        },
        login: {
            title: 'மீண்டும் வருக',
            subtitle: 'உங்கள் கோட்பந்து கணக்கில் உள்நுழையவும்',
            email: 'மின்னஞ்சல் முகவரி',
            password: 'கடவுச்சொல்',
            rememberMe: 'என்னை நினைவில் கொள்',
            forgotPassword: 'கடவுச்சொல்லை மறந்துவிட்டீர்களா?',
            signIn: 'உள்நுழைய',
            signingIn: 'உள்நுழைகிறது...',
            noAccount: "கணக்கு இல்லையா?",
            createAccount: 'கணக்கை உருவாக்கவும்',
            demoCredentials: 'டெமோ சான்றுகள்:',
        },
        signup: {
            title: 'கணக்கை உருவாக்கவும்',
            subtitle: 'இன்றே கோட்பந்துவில் இணையுங்கள்',
            firstName: 'முதல் பெயர்',
            lastName: 'கடைசி பெயர்',
            email: 'மின்னஞ்சல் முகவரி',
            password: 'கடவுச்சொல்',
            createAccount: 'கணக்கை உருவாக்கவும்',
            creating: 'கணக்கு உருவாக்கப்படுகிறது...',
            hasAccount: 'ஏற்கனவே கணக்கு உள்ளதா?',
            signIn: 'உள்நுழைய',
        },
        documents: {
            title: 'எனது ஆவணங்கள்',
            empty: 'ஆவணங்கள் எதுவும் இல்லை.',
            headers: {
                name: 'ஆவணத்தின் பெயர்',
                date: 'தேதி',
                type: 'வகை',
                status: 'நிலை',
                actions: 'செயல்கள்',
            },
        },
        processing: {
            title: 'ஆவணத்தை பகுப்பாய்வு செய்கிறது',
            step1: 'ஆவண அமைப்பை ஸ்கேன் செய்கிறது...',
            step2: 'சட்டப் பிரிவுகளை அடையாளம் காணுதல்...',
            step3: 'சிக்கலான மொழியை எளிதாக்குதல்...',
            step4: 'சுருக்கத்தை உருவாக்குகிறது...',
            step5: 'ஆலோசனையைத் தயார் செய்கிறது...',
            complete: 'பகுப்பாய்வு முடிந்தது!',
        },
        results: {
            title: 'பகுப்பாய்வு முடிவுகள்',
            back: 'முகப்புக்குத் திரும்பு',
            tabs: {
                simplification: 'எளிமைப்படுத்தல்',
                summary: 'சுருக்கம்',
                advisory: 'சட்ட ஆலோசனை',
                chat: 'AI இடம் கேளுங்கள்',
            },
            simplification: {
                original: 'அசல் உரை',
                simplified: 'எளிமைப்படுத்தப்பட்ட பதிப்பு',
            },
            summary: {
                issue: 'சட்ட சிக்கல்',
                facts: 'முக்கிய உண்மைகள்',
                arguments: 'வாதங்கள்',
                conclusion: 'முடிவு',
            },
            advisory: {
                rights: 'உங்கள் உரிமைகள்',
                actions: 'பரிந்துரைக்கப்பட்ட நடவடிக்கைகள்',
                risk: 'ஆபத்து மதிப்பீடு',
            },
        },
    },
};

import { translateText as bhashiniTranslate } from '../services/bhashini';

export function LanguageProvider({ children }) {
    const [language, setLanguage] = useState('en');
    const [apiKey, setApiKey] = useState(import.meta.env.VITE_BHASHINI_API_KEY);

    const changeLanguage = (langCode) => {
        setLanguage(langCode);
    };

    const t = (key) => {
        const keys = key.split('.');
        let value = translations[language];

        for (const k of keys) {
            value = value?.[k];
        }

        return value || key;
    };

    const translate = async (text, targetLang) => {
        if (!text) return '';
        if (targetLang === 'en') return text; // Assuming source is English
        return await bhashiniTranslate(text, 'en', targetLang);
    };

    return (
        <LanguageContext.Provider value={{ language, changeLanguage, t, apiKey, setApiKey, translate }}>
            {children}
        </LanguageContext.Provider>
    );
}

export function useLanguage() {
    const context = useContext(LanguageContext);
    if (!context) {
        throw new Error('useLanguage must be used within a LanguageProvider');
    }
    return context;
}
